<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7aC8ot3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7aC8ot3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7aC8ot3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7aC8ot3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7aC8ot3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7aC8ot3',
    'container.build_id' => 'd116048a',
    'container.build_time' => 1602064625,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7aC8ot3');
